=== edrlab/lcp-server/pkg/check/data/status.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://readium.org/lcp-specs/schema/status.schema.json",
  "title": "Readium LCP Status Document",
  "type": "object",
  "properties": {
    "id": {
      "description": "Unique identifier for the License Document associated to the Status Document.",
      "type": "string"
    },
    "status": {
      "description": "Current status of the License.",
      "type": "string",
      "enum": [
        "ready",
        "active",
        "revoked",
        "returned",
        "cancelled",
        "expired"
      ]
    },
    "message": {
      "description": "A message meant to be displayed to the User regarding the current status of the license.",
      "type": "string"
    },
    "updated": {
      "type": "object",
      "properties": {
        "license": {
          "description": "Time and Date when the License Document was last updated",
          "type": "string",
          "format": "date-time"
        },
        "status": {
          "description": "Time and Date when the Status Document was last updated",
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "license",
        "status"
      ]
    },
    "links": {
      "type": "array",
      "items": {
        "$ref": "link.schema.json"
      },
      "uniqueItems": true
    },
    "potential_rights": {
      "type": "object",
      "properties": {
        "end": {
          "description": "Date and time when the license ends",
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "events": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "description": "Identifies the type of event",
            "type": "string",
            "enum": [
              "register",
              "renew",
              "return",
              "revoke",
              "cancel"
            ]
          },
          "name": {
            "description": "Name of the client, as provided by the client during an interaction",
            "type": "string"
          },
          "id": {
            "description": "Identifies the client, as provided by the client during an interaction",
            "type": "string"
          },
          "timestamp": {
            "description": "Time and date when the event occurred",
            "type": "string",
            "format": "date-time"
          }
        }
      }
    }
  },
  "required": [
    "id",
    "status",
    "message",
    "updated",
    "links"
  ],
  "allOf": [
    {
      "description": "An LCP Status Document MUST contain a link to a license",
      "type": "object",
      "properties": {
        "links": {
          "type": "array",
          "contains": {
            "type": "object",
            "properties": {
              "href": {
                "type": "string",
                "format": "uri"
              },
              "rel": {
                "anyOf": [
                  {
                    "type": "string",
                    "const": "license"
                  },
                  {
                    "type": "array",
                    "contains": {
                      "type": "string",
                      "const": "license"
                    }
                  }
                ]
              }
            }
          }
        }
      }
    }
  ]
}

=== edrlab/lcp-server/test/status1.json
{"id":"653673ed-ef9d-4987-a0cb-d9b017de4bbc","status":"ready","updated":{"license":"2023-01-14T14:02:43Z","status":"2023-01-14T14:02:43Z"},"message":"ready","links":[{"rel":"license","href":"http://192.168.0.42:8991/api/v1/licenses/653673ed-ef9d-4987-a0cb-d9b017de4bbc","type":"application/vnd.readium.lcp.license.v1.0+json"},{"rel":"register","href":"http://192.168.0.42:8990/licenses/653673ed-ef9d-4987-a0cb-d9b017de4bbc/register{?id,name}","type":"application/vnd.readium.license.status.v1.0+json","templated":true},{"rel":"return","href":"http://192.168.0.42:8990/licenses/653673ed-ef9d-4987-a0cb-d9b017de4bbc/return{?id,name}","type":"application/vnd.readium.license.status.v1.0+json","templated":true},{"rel":"renew","href":"https://www.google.com","type":"text/html"}],"potential_rights":{"end":"2023-02-13T14:02:43Z"}}
